// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.VBox vbox1;
    
    private Gtk.ComboBox combobox1;
    
    private Gtk.HBox hbox2;
    
    private Gtk.Label label1;
    
    private Gtk.Entry txtFrom;
    
    private Gtk.HBox hbox3;
    
    private Gtk.Label label2;
    
    private Gtk.Entry txtTo;
    
    private Gtk.HBox hbox4;
    
    private Gtk.Button button1;
    
    private Gtk.Button btnClose;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("WR Translator");
        this.Icon = Stetic.IconLoader.LoadIcon(this, "gtk-select-color", Gtk.IconSize.Menu, 16);
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        this.BorderWidth = ((uint)(9));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.combobox1 = Gtk.ComboBox.NewText();
        this.combobox1.AppendText(Mono.Unix.Catalog.GetString("English Italian"));
        this.combobox1.AppendText(Mono.Unix.Catalog.GetString("Italian English"));
        this.combobox1.AppendText(Mono.Unix.Catalog.GetString("English French"));
        this.combobox1.AppendText(Mono.Unix.Catalog.GetString("French English"));
        this.combobox1.AppendText(Mono.Unix.Catalog.GetString("English Spanish"));
        this.combobox1.AppendText(Mono.Unix.Catalog.GetString("Spanish English"));
        this.combobox1.AppendText(Mono.Unix.Catalog.GetString("Espanol Francais"));
        this.combobox1.AppendText(Mono.Unix.Catalog.GetString("Francais Espanol"));
        this.combobox1.AppendText(Mono.Unix.Catalog.GetString("Espanol Portugues"));
        this.combobox1.AppendText(Mono.Unix.Catalog.GetString("Portugues Espanol"));
        this.combobox1.Name = "combobox1";
        this.vbox1.Add(this.combobox1);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.combobox1]));
        w1.Position = 0;
        w1.Expand = false;
        w1.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("From:");
        this.hbox2.Add(this.label1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox2[this.label1]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.txtFrom = new Gtk.Entry();
        this.txtFrom.CanFocus = true;
        this.txtFrom.Name = "txtFrom";
        this.txtFrom.IsEditable = true;
        this.txtFrom.InvisibleChar = '●';
        this.hbox2.Add(this.txtFrom);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox2[this.txtFrom]));
        w3.Position = 1;
        this.vbox1.Add(this.hbox2);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
        w4.Position = 1;
        w4.Expand = false;
        w4.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox3 = new Gtk.HBox();
        this.hbox3.Name = "hbox3";
        this.hbox3.Spacing = 6;
        // Container child hbox3.Gtk.Box+BoxChild
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("To:");
        this.hbox3.Add(this.label2);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox3[this.label2]));
        w5.Position = 0;
        w5.Expand = false;
        w5.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.txtTo = new Gtk.Entry();
        this.txtTo.CanFocus = true;
        this.txtTo.Name = "txtTo";
        this.txtTo.IsEditable = true;
        this.txtTo.InvisibleChar = '●';
        this.hbox3.Add(this.txtTo);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox3[this.txtTo]));
        w6.Position = 1;
        this.vbox1.Add(this.hbox3);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
        w7.Position = 2;
        w7.Expand = false;
        w7.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox4 = new Gtk.HBox();
        this.hbox4.Name = "hbox4";
        this.hbox4.Spacing = 6;
        // Container child hbox4.Gtk.Box+BoxChild
        this.button1 = new Gtk.Button();
        this.button1.CanFocus = true;
        this.button1.Name = "button1";
        this.button1.UseStock = true;
        this.button1.UseUnderline = true;
        this.button1.Label = "gtk-ok";
        this.hbox4.Add(this.button1);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox4[this.button1]));
        w8.Position = 0;
        w8.Expand = false;
        w8.Fill = false;
        // Container child hbox4.Gtk.Box+BoxChild
        this.btnClose = new Gtk.Button();
        this.btnClose.CanFocus = true;
        this.btnClose.Name = "btnClose";
        this.btnClose.UseStock = true;
        this.btnClose.UseUnderline = true;
        this.btnClose.Label = "gtk-close";
        this.hbox4.Add(this.btnClose);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox4[this.btnClose]));
        w9.Position = 1;
        w9.Expand = false;
        w9.Fill = false;
        this.vbox1.Add(this.hbox4);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
        w10.Position = 3;
        w10.Expand = false;
        w10.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 460;
        this.DefaultHeight = 151;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.txtFrom.KeyPressEvent += new Gtk.KeyPressEventHandler(this.OnTxtFromKeyPressEvent);
        this.txtFrom.KeyReleaseEvent += new Gtk.KeyReleaseEventHandler(this.OnTxtFromKeyReleaseEvent);
        this.button1.Clicked += new System.EventHandler(this.OnButton1Clicked);
        this.btnClose.Clicked += new System.EventHandler(this.OnBtnCloseClicked);
    }
}
